title: Awesome Effective Altruism
email: henry@henrystanley.com
description: >-
  A curated list of resources on how to do the most good
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://effectivealtruism.rocks" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
